Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -72,10 +72,21 @@ jobs:
       #with:
         #dotnet-version: '6.x' # Specify the .NET version
     
-    - name: Install ReportGenerator
+    #- name: Install ReportGenerator
+      #run: |
+        ##sudo apt install dotnet-host
+        #sudo dotnet tool install -g dotnet-reportgenerator-globaltool
+
+    - name: Install ReportGenerator if not present
       run: |
-        #sudo apt install dotnet-host
-        sudo dotnet tool install -g dotnet-reportgenerator-globaltool
+        if ! command -v reportgenerator &> /dev/null
+        then
+          echo "ReportGenerator not found, installing..."
+          sudo dotnet tool install -g dotnet-reportgenerator-globaltool
+        else
+          echo "ReportGenerator already installed."
+        fi
+      shell: bash
 
     #- name: Install ReportGenerator
       #run: |
